"""empty message

Revision ID: 9fc3c9b31622
Revises: b4f103e21e4e
Create Date: 2020-12-23 01:29:40.211570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc3c9b31622'
down_revision = 'b4f103e21e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
