"""empty message

Revision ID: aa19a8444a8b
Revises: de4ded2cd779
Create Date: 2020-12-23 00:29:02.589998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa19a8444a8b'
down_revision = 'de4ded2cd779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.drop_column('product', 'purchase_id')
    op.add_column('purchase', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'product_id')
    op.add_column('product', sa.Column('purchase_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('product_ibfk_1', 'product', 'purchase', ['purchase_id'], ['id'])
    # ### end Alembic commands ###
