"""empty message

Revision ID: b4f103e21e4e
Revises: aa19a8444a8b
Create Date: 2020-12-23 01:24:00.264123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f103e21e4e'
down_revision = 'aa19a8444a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
