"""empty message

Revision ID: de4ded2cd779
Revises: ecc03103035c
Create Date: 2020-12-23 00:22:37.985638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4ded2cd779'
down_revision = 'ecc03103035c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
