"""empty message

Revision ID: ecc03103035c
Revises: 59d0d8ee4bdf
Create Date: 2020-12-23 00:22:10.078572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc03103035c'
down_revision = '59d0d8ee4bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
